version: '3'
services:
  webdjango:
    build:
      context: webdjango/
    restart: always
    command: ["gunicorn", "webdjango.wsgi", "-b", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - ./webdjango:/webdjango

  webflask:
    build:
      context: webflask/
    restart: always
    command: ["python", "webflask.py"]
    ports:
      - "8001:8001"
    volumes:
      - ./webflask:/webflask

  webgo:
    build:
      context: webgo/
    restart: always
    ports:
      - "8002:8002"
    volumes:
      - ./webgo:/webgo

  webnode:
    build:
      context: webnode/
    restart: always
    command: ["npm", "start"]
    ports:
      - "8003:8003"
    volumes:
      - ./webnode:/webnode

  nginx:
    build:
      context: nginx/
    restart: always
    ports:
      - "80:80"